name: Web app e2e tests

on:
  workflow_dispatch:
    inputs:
      test-environment:
        description: "Environment to run tests against"
        required: true
        type: choice
        default: "qa"
        options:
          - prod
          - qa

      browser:
        description: "Browser to run tests against"
        required: true
        type: choice
        default: "chromium"
        options:
          - chromium
          - webkit
          - firefox

      test-project:
        description: "Test suite to run"
        required: true
        type: choice
        default: "health-check"
        options:
          - health-check
  workflow_run:
    workflows: ["Deploy Web App"]
    types:
      - completed
    branches:
      - qa
      - main

jobs:
  E2E-Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checking variables
        run: |
          echo "Deployment Environment from workflow: ${{ github.event.workflow_run.outputs.test-environment }}"
          echo "Deployment Environment from dispatch: ${{ github.event.inputs.test-environment  }}"
