name: Deploy Web App
on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test-environment2: ${{ steps.set-environment.outputs.test-environment2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment for Testing
        id: set-environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=test-environment2::prod"
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "::set-output name=test-environment2::qa"
          else
            echo "::set-output name=test-environment2::none"
          fi
             
      - name: Change build env vari
        run: |
          echo "test-environment=qa" >> "$GITHUB_ENV"
          
      - name: Run automated tests on SauceLabs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'dssalaza',
              repo: 'csis-3380-pagination',
              workflow_id: 'e2e-tests.yml',
              ref: 'main',
              inputs: { 
                test-environment: "${{ env.test-environment }}"
              }
            })
