name: Deploy Web App
on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test-environment2: ${{ steps.set-environment.outputs.test-environment2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment for Testing
        id: set-environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=test-environment2::prod"
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "::set-output name=test-environment2::qa"
          else
            echo "::set-output name=test-environment2::none"
          fi
             
  call_reusable:
    needs:
      - build
    uses: dssalaza/csis-3380-pagination/.github/workflows/e2e-tests.yml@main
    with:
      test-environment2: ${{ needs.build.outputs.test-environment2 }}
