name: Deploy Web App
on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test-environment: ${{ steps.set-environment.outputs.test-environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment for Testing
        id: set-environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=test-environment::prod"
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "::set-output name=test-environment::qa"
          else
            echo "::set-output name=test-environment::none"
          fi
             
      - name: Install Yarn
        run: npm install -g yarn
