name: Deploy Web App
on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # outputs:
      # test-environment2: ${{ steps.set-environment.outputs.test-environment2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment for Testing
        id: set-environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "test-environment=prod" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "test-environment=qa" >> "$GITHUB_ENV"
          else
            echo "test-environment=prod" >> "$GITHUB_ENV"
          fi
             
      - name: Run automated tests on SauceLabs
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'dssalaza',
              repo: 'csis-3380-pagination',
              workflow_id: 'webApp.e2e.yml',
              ref: 'main',
              inputs: { 
                environment: "prod",
                browser: "chromium",
                test_project: "health-check"
              }
            })
